---
# tasks file for wordpres

#- name: Ensure "{{ wordpress_root }}" directory exist
#  file:
#    path: "{{ wordpress_root }}"
#    state: directory

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www"
    remote_src: yes
#    creates: "{{ wordpress_root }}"

- name: Set ownership
  file:
    path: "{{ wordpress_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set up wp-config
  template:
    src: "wp-config.php.tpl"
    dest: "{{ wordpress_root }}/wp-config.php"
