version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: db
    networks:
      - backend
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_pass
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: wordpress
    networks:
      - backend
      - frontend
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html


  reverse_proxy:
    depends_on:
      - wordpress
    image: nginx
    container_name: reverse_proxy
    networks:
      - frontend
    restart: always
    ports:
      - 80:80
    volumes:
      - ${PWD}/proxy.conf:/etc/nginx/conf.d/default.conf

volumes:
  wordpress:
  db:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
